# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb2385855b65490a7f8c6525d15d1c60a509a88dd8a06bad8587ff97f92d22f99d9d1046feadc7ccaa52e2cd2c5be50188adbd4f70d46dc0fbf08e0da8d59515
  demo_phone_number: "+79991112233"
  demo_code: "1234"

test:
  secret_key_base: d33bc8d917795c9baa5a1dc55a34967e3bb12608ff2a9ae2dea514ef09a5b41d107f66839b0d3572dc80378e811d0ffa13c13f929d14094648fee34154f2413f
  demo_phone_number: "+79991112233"
  demo_code: "1234"

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  demo_phone_number: "<%= ENV["DEMO_PHONE_NUMBER"] %>"
  demo_code: "<%= ENV["DEMO_CODE"] %>"
  sms_ru_api_id: <%= ENV["SMS_RU_API_ID"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_s3_bucket_name: <%= ENV["AWS_S3_BUCKET_NAME"] %>
  domain_url: <%= ENV["DOMAIN_URL"] %>
  google_key: <%= ENV["GOOGLE_KEY"] %>
  google_secret: <%= ENV["GOOGLE_SECRET"] %>
  google_access_token: <%= ENV["GOOGLE_ACCESS_TOKEN"] %>
  google_refresh_token: <%= ENV["GOOGLE_REFRESH_TOKEN"] %>
